// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ePrevzem.Infrastructure.Persistence;

#nullable disable

namespace ePrevzem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EPrevzemDbContext))]
    [Migration("20260518215900_Identity_RefactorPreFilledInfo")]
    partial class Identity_RefactorPreFilledInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ePrevzem.Domain.Identity.OrganizationAdminAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("organization_admin_accounts", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.ProvisioningCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByOrganizationAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_organization_admin_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("IsReprovisioningOfEmployeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("is_reprovisioning_of_employee_account_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid?>("RedeemedIntoEmployeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("redeemed_into_employee_account_id");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roles");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByOrganizationAdminId");

                    b.ToTable("provisioning_codes", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("OrganizationAdminAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_admin_account_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("SystemAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_admin_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationAdminAccountId");

                    b.HasIndex("SystemAdminId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_refresh_tokens_single_actor", "(system_admin_id IS NOT NULL AND organization_admin_account_id IS NULL) OR (system_admin_id IS NULL AND organization_admin_account_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.SystemAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("system_admins", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Lockers.Locker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsServiceable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_serviceable");

                    b.Property<int>("LockerNumber")
                        .HasColumnType("integer")
                        .HasColumnName("locker_number");

                    b.Property<Guid>("PickupStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_station_id");

                    b.HasKey("Id");

                    b.HasIndex("PickupStationId");

                    b.ToTable("lockers", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Lockers.PickupStation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("pickup_stations", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Lockers.StationClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PickupStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_station_id");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.HasKey("Id");

                    b.HasIndex("PickupStationId")
                        .IsUnique()
                        .HasFilter("released_at IS NULL");

                    b.ToTable("station_claims", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultPickupDuration")
                        .HasColumnType("integer")
                        .HasColumnName("default_pickup_duration_in_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_number");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tax_number");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.ProvisioningCode", b =>
                {
                    b.HasOne("ePrevzem.Domain.Identity.OrganizationAdminAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByOrganizationAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ePrevzem.Domain.Identity.PersonalInfo", "PreFilledInfo", b1 =>
                        {
                            b1.Property<Guid>("ProvisioningCodeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("pre_filled_email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("pre_filled_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("pre_filled_last_name");

                            b1.HasKey("ProvisioningCodeId");

                            b1.ToTable("provisioning_codes");

                            b1.WithOwner()
                                .HasForeignKey("ProvisioningCodeId");
                        });

                    b.Navigation("PreFilledInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("ePrevzem.Domain.Identity.OrganizationAdminAccount", null)
                        .WithMany()
                        .HasForeignKey("OrganizationAdminAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ePrevzem.Domain.Identity.SystemAdmin", null)
                        .WithMany()
                        .HasForeignKey("SystemAdminId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ePrevzem.Domain.Lockers.Locker", b =>
                {
                    b.HasOne("ePrevzem.Domain.Lockers.PickupStation", null)
                        .WithMany("Lockers")
                        .HasForeignKey("PickupStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ePrevzem.Domain.Lockers.StationClaim", b =>
                {
                    b.OwnsOne("ePrevzem.Domain.Lockers.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("StationClaimId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_address");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_city");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_house_number");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("location_latitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("location_longitude");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_zip_code");

                            b1.HasKey("StationClaimId");

                            b1.ToTable("station_claims");

                            b1.WithOwner()
                                .HasForeignKey("StationClaimId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("ePrevzem.Domain.Lockers.PickupStation", b =>
                {
                    b.Navigation("Lockers");
                });
#pragma warning restore 612, 618
        }
    }
}
