// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ePrevzem.Infrastructure.Persistence;

#nullable disable

namespace ePrevzem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EPrevzemDbContext))]
    partial class EPrevzemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ePrevzem.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorCitizenUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_citizen_user_id");

                    b.Property<Guid?>("ActorEmployeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_employee_account_id");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_kind");

                    b.Property<Guid?>("ActorOrganizationAdminAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_organization_admin_account_id");

                    b.Property<Guid?>("ActorSystemAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_system_admin_id");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_kind");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ActorCitizenUserId");

                    b.HasIndex("ActorEmployeeAccountId");

                    b.HasIndex("ActorOrganizationAdminAccountId");

                    b.HasIndex("ActorSystemAdminId");

                    b.HasIndex("OrganizationId", "OccurredAt");

                    b.HasIndex("TargetKind", "TargetId");

                    b.ToTable("audit_log_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_log_entries_actor", "(\n    actor_kind = 'System'\n    AND actor_citizen_user_id IS NULL\n    AND actor_employee_account_id IS NULL\n    AND actor_organization_admin_account_id IS NULL\n    AND actor_system_admin_id IS NULL\n)\nOR (\n    actor_kind = 'Citizen'\n    AND actor_citizen_user_id IS NOT NULL\n    AND actor_employee_account_id IS NULL\n    AND actor_organization_admin_account_id IS NULL\n    AND actor_system_admin_id IS NULL\n)\nOR (\n    actor_kind = 'Employee'\n    AND actor_citizen_user_id IS NULL\n    AND actor_employee_account_id IS NOT NULL\n    AND actor_organization_admin_account_id IS NULL\n    AND actor_system_admin_id IS NULL\n)\nOR (\n    actor_kind = 'OrganizationAdmin'\n    AND actor_citizen_user_id IS NULL\n    AND actor_employee_account_id IS NULL\n    AND actor_organization_admin_account_id IS NOT NULL\n    AND actor_system_admin_id IS NULL\n)\nOR (\n    actor_kind = 'SystemAdmin'\n    AND actor_citizen_user_id IS NULL\n    AND actor_employee_account_id IS NULL\n    AND actor_organization_admin_account_id IS NULL\n    AND actor_system_admin_id IS NOT NULL\n)");
                        });
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.CitizenActivationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CitizenUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("citizen_user_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.HasKey("Id");

                    b.HasIndex("CitizenUserId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("citizen_activation_codes", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.CitizenUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Emso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emso");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset>("OnboardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarded_at");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("Emso")
                        .IsUnique();

                    b.ToTable("citizen_users", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.DeviceChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("DeviceKind")
                        .HasColumnType("integer")
                        .HasColumnName("device_kind");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ConsumedAt");

                    b.ToTable("device_challenges", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.EmployeeAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedFromProvisioningCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_from_provisioning_code_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("_roles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roles");

                    b.Property<string>("_stationAccess")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("station_access");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("email IS NOT NULL");

                    b.ToTable("employee_accounts", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.OrganizationAdminAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("organization_admin_accounts", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.ProvisioningCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByOrganizationAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_organization_admin_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("IsReprovisioningOfEmployeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("is_reprovisioning_of_employee_account_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid?>("RedeemedIntoEmployeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("redeemed_into_employee_account_id");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roles");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByOrganizationAdminId");

                    b.ToTable("provisioning_codes", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CitizenUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("citizen_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EmployeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_account_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("OrganizationAdminAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_admin_account_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("SystemAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_admin_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("CitizenUserId");

                    b.HasIndex("EmployeeAccountId");

                    b.HasIndex("OrganizationAdminAccountId");

                    b.HasIndex("SystemAdminId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_refresh_tokens_single_actor", "(CASE WHEN system_admin_id IS NULL THEN 0 ELSE 1 END + CASE WHEN organization_admin_account_id IS NULL THEN 0 ELSE 1 END + CASE WHEN employee_account_id IS NULL THEN 0 ELSE 1 END + CASE WHEN citizen_user_id IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.SystemAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("system_admins", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Lockers.Locker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("BoxId")
                        .HasColumnType("bigint")
                        .HasColumnName("box_id");

                    b.Property<bool>("IsServiceable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_serviceable");

                    b.Property<int>("LockerNumber")
                        .HasColumnType("integer")
                        .HasColumnName("locker_number");

                    b.Property<Guid>("PickupStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_station_id");

                    b.HasKey("Id");

                    b.HasIndex("PickupStationId");

                    b.ToTable("lockers", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Lockers.PickupStation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("pickup_stations", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Lockers.StationClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PickupStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_station_id");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.HasKey("Id");

                    b.HasIndex("PickupStationId")
                        .IsUnique()
                        .HasFilter("released_at IS NULL");

                    b.ToTable("station_claims", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultPickupDuration")
                        .HasColumnType("integer")
                        .HasColumnName("default_pickup_duration_in_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_number");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tax_number");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Pickups.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByEmployeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_employee_account_id");

                    b.Property<Guid?>("CreatedByOrganizationAdminAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_organization_admin_account_id");

                    b.Property<DateTimeOffset?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RecipientCitizenUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_citizen_user_id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetPickupStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_pickup_station_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByEmployeeAccountId");

                    b.HasIndex("CreatedByOrganizationAdminAccountId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RecipientCitizenUserId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("TargetPickupStationId");

                    b.ToTable("packages", null, t =>
                        {
                            t.HasCheckConstraint("ck_packages_exactly_one_creator", "(created_by_employee_account_id IS NOT NULL) <> (created_by_organization_admin_account_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ePrevzem.Domain.Pickups.Placement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EndReason")
                        .HasColumnType("text")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid?>("EndedByCitizenUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ended_by_citizen_user_id");

                    b.Property<Guid?>("EndedByEmployeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ended_by_employee_account_id");

                    b.Property<Guid>("LockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("locker_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpenedByEmployeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_employee_account_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.HasKey("Id");

                    b.HasIndex("EndedByCitizenUserId");

                    b.HasIndex("EndedByEmployeeAccountId");

                    b.HasIndex("LockerId")
                        .IsUnique()
                        .HasFilter("ended_at IS NULL");

                    b.HasIndex("OpenedByEmployeeAccountId");

                    b.HasIndex("PackageId")
                        .IsUnique()
                        .HasFilter("ended_at IS NULL");

                    b.ToTable("placements", (string)null);
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.CitizenActivationCode", b =>
                {
                    b.HasOne("ePrevzem.Domain.Identity.CitizenUser", null)
                        .WithMany()
                        .HasForeignKey("CitizenUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.CitizenUser", b =>
                {
                    b.OwnsMany("ePrevzem.Domain.Identity.CitizenDevice", "Devices", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CitizenUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("citizen_user_id");

                            b1.Property<string>("DeviceFingerprint")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("device_fingerprint");

                            b1.Property<string>("Label")
                                .HasColumnType("text")
                                .HasColumnName("label");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("public_key");

                            b1.Property<DateTimeOffset>("RegisteredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("registered_at");

                            b1.Property<DateTimeOffset?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<Guid>("citizen_user_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("citizen_user_id");

                            b1.ToTable("citizen_devices", null, t =>
                                {
                                    t.Property("citizen_user_id")
                                        .HasColumnName("citizen_user_id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("citizen_user_id");
                        });

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.EmployeeAccount", b =>
                {
                    b.OwnsMany("ePrevzem.Domain.Identity.EmployeeDevice", "Devices", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("DeviceFingerprint")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("device_fingerprint");

                            b1.Property<Guid>("EmployeeAccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("employee_account_id");

                            b1.Property<string>("Label")
                                .HasColumnType("text")
                                .HasColumnName("label");

                            b1.Property<DateTimeOffset>("ProvisionedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("provisioned_at");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("public_key");

                            b1.Property<DateTimeOffset?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<Guid>("employee_account_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("employee_account_id");

                            b1.ToTable("employee_devices", null, t =>
                                {
                                    t.Property("employee_account_id")
                                        .HasColumnName("employee_account_id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("employee_account_id");
                        });

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.ProvisioningCode", b =>
                {
                    b.HasOne("ePrevzem.Domain.Identity.OrganizationAdminAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByOrganizationAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ePrevzem.Domain.Identity.PersonalInfo", "PreFilledInfo", b1 =>
                        {
                            b1.Property<Guid>("ProvisioningCodeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("pre_filled_email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("pre_filled_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("pre_filled_last_name");

                            b1.HasKey("ProvisioningCodeId");

                            b1.ToTable("provisioning_codes");

                            b1.WithOwner()
                                .HasForeignKey("ProvisioningCodeId");
                        });

                    b.Navigation("PreFilledInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("ePrevzem.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("ePrevzem.Domain.Identity.CitizenUser", null)
                        .WithMany()
                        .HasForeignKey("CitizenUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ePrevzem.Domain.Identity.EmployeeAccount", null)
                        .WithMany()
                        .HasForeignKey("EmployeeAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ePrevzem.Domain.Identity.OrganizationAdminAccount", null)
                        .WithMany()
                        .HasForeignKey("OrganizationAdminAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ePrevzem.Domain.Identity.SystemAdmin", null)
                        .WithMany()
                        .HasForeignKey("SystemAdminId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ePrevzem.Domain.Lockers.Locker", b =>
                {
                    b.HasOne("ePrevzem.Domain.Lockers.PickupStation", null)
                        .WithMany("Lockers")
                        .HasForeignKey("PickupStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ePrevzem.Domain.Lockers.StationClaim", b =>
                {
                    b.OwnsOne("ePrevzem.Domain.Lockers.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("StationClaimId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_address");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_city");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_house_number");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("location_latitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("location_longitude");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_zip_code");

                            b1.HasKey("StationClaimId");

                            b1.ToTable("station_claims");

                            b1.WithOwner()
                                .HasForeignKey("StationClaimId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("ePrevzem.Domain.Pickups.Package", b =>
                {
                    b.HasOne("ePrevzem.Domain.Identity.EmployeeAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByEmployeeAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ePrevzem.Domain.Identity.OrganizationAdminAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByOrganizationAdminAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ePrevzem.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ePrevzem.Domain.Identity.CitizenUser", null)
                        .WithMany()
                        .HasForeignKey("RecipientCitizenUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ePrevzem.Domain.Lockers.PickupStation", null)
                        .WithMany()
                        .HasForeignKey("TargetPickupStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ePrevzem.Domain.Pickups.Placement", b =>
                {
                    b.HasOne("ePrevzem.Domain.Identity.CitizenUser", null)
                        .WithMany()
                        .HasForeignKey("EndedByCitizenUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ePrevzem.Domain.Identity.EmployeeAccount", null)
                        .WithMany()
                        .HasForeignKey("EndedByEmployeeAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ePrevzem.Domain.Lockers.Locker", null)
                        .WithMany()
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ePrevzem.Domain.Identity.EmployeeAccount", null)
                        .WithMany()
                        .HasForeignKey("OpenedByEmployeeAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ePrevzem.Domain.Pickups.Package", null)
                        .WithMany("Placements")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ePrevzem.Domain.Lockers.PickupStation", b =>
                {
                    b.Navigation("Lockers");
                });

            modelBuilder.Entity("ePrevzem.Domain.Pickups.Package", b =>
                {
                    b.Navigation("Placements");
                });
#pragma warning restore 612, 618
        }
    }
}
