name: eosebna-build
"on":
  pull_request:
jobs:
  build:
    name: eosebna-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            eosebna:
              - "sitrust-mock/eosebna_mobile/**"
              - ".github/workflows/eosebna-mobile.yml"
      - uses: subosito/flutter-action@v2
        if: steps.changes.outputs.eosebna == 'true'
        with:
          channel: stable
      - if: steps.changes.outputs.eosebna == 'true'
        working-directory: sitrust-mock/eosebna_mobile
        run: flutter pub get
      - if: steps.changes.outputs.eosebna == 'true'
        working-directory: sitrust-mock/eosebna_mobile
        run: flutter analyze
      - if: steps.changes.outputs.eosebna == 'true'
        working-directory: sitrust-mock/eosebna_mobile
        run: flutter test
