name: sitrust-backend-build
"on":
  pull_request:
jobs:
  build:
    name: sitrust-backend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            sitrust-backend:
              - "sitrust-mock/backend/**"
              - "sitrust-mock/sitrust-mock.sln"
              - ".github/workflows/sitrust-backend.yml"
      - uses: actions/setup-dotnet@v4
        if: steps.changes.outputs.sitrust-backend == 'true'
        with:
          dotnet-version: "9.0.x"
      - if: steps.changes.outputs.sitrust-backend == 'true'
        run: dotnet build sitrust-mock/sitrust-mock.sln
      - if: steps.changes.outputs.sitrust-backend == 'true'
        run: dotnet test sitrust-mock/backend/SiTrustMock.Tests
